#!/bin/bash
echo "📱 Surveillance des logs iOS en temps réel"
echo "=========================================="
echo "🔧 Utilisez cette commande dans un terminal séparé:"
echo "   xcrun simctl spawn booted log stream --predicate 'subsystem contains \"com.apple.WebKit\"'"
echo ""
echo "💡 Ou pour tous les logs de l'app:"
echo "   xcrun simctl spawn booted log stream --predicate 'process == \"Vision Picturale\"'"
echo ""
echo "🎯 Recherchez ces messages clés:"
echo "   • 'Navigation vers:' - Début de navigation"
echo "   • 'Application ... chargée' - Fin de chargement"
echo "   • 'Erreur de navigation:' - Problèmes détectés"
echo "   • 'beforeunload' - Rechargements non désirés"
